# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# pre-commit install        啟用指定的 git hook
# pre-commit autoupdate     更新以下 repo 的版本
# pre-commit run --all-files 全檔案檢查，而不是只有被提交的檔案
# pre-commit run --hook-stage manual --all-files  如果需要額外檢查 manual 的項目
# pre-commit run <hook_id> --all-files 只檢查特定一個 hook 是否通過

# SKIP=check-added-large-files git commit -m "提交訊息"    暫時跳過特定 hock
# git commit --no-verify 或者 git commit -n               跳過所有 commit hock

default_install_hook_types: [pre-commit, commit-msg]

default_language_version:
  python: python3.13

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=8192"]
      - id: check-ast
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-xml

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-yaml
        args:
          - --autofix
          - --preserve-quotes
          - --indent=2
          - --offset=2

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        args: ["-o", "array_auto_collapse=false", "-o", "indent_string=    "]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.0
    hooks:
      - id: uv-lock

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.2.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
        additional_dependencies: [cz-conventional-gitmoji]

  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.6.1
    hooks:
      - id: conventional-gitmoji
        stages: [commit-msg]
